version: '3'
services:
    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: 'sqlx'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
        cap_add:
            - SYS_NICE

volumes:
    my-db: